<a href="https://colab.research.google.com/github/orinbou/MathPythonColab/blob/main/chapter/%E7%AC%AC11%E5%9B%9E%E3%80%80Python%E3%81%A7%E7%B7%9A%E5%BD%A2%E4%BB%A3%E6%95%B0%EF%BC%81%EF%BD%9E%E8%A1%8C%E5%88%97%E7%B7%A8%EF%BC%88%E5%9F%BA%E7%A4%8E%E3%83%BB%E5%BE%8C%E7%B7%A8%EF%BC%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 目標1： 行列の内積を求める

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[-2, 3],
              [1, 5]])

print(A @ B)
print(np.dot(A, B))

[[ 0 13]
 [-2 29]]
[[ 0 13]
 [-2 29]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2行3列
B = np.array([[-2, 3, 4, -3],
              [1, 5, 1, 2],
              [-3, -1, 2, 4]])  # 3行4列

print(A @ B)
print(B @ A)

[[ -9  10  12  13]
 [-21  31  33  22]]


ValueError: ignored

# 目標2： 二次元配列での@演算子、dot関数、inner関数の違いを確認する

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[-2, 3],
              [1, 5]])

print("(A @ B)")
print(A @ B)
print("np.dot(A, B)")
print(np.dot(A, B))
print("np.inner(A, B)")
print(np.inner(A, B))
print("np.inner(A, B.T)")
print(np.inner(A, B.T))

(A @ B)
[[ 0 13]
 [-2 29]]
np.dot(A, B)
[[ 0 13]
 [-2 29]]
np.inner(A, B)
[[ 4 11]
 [ 6 23]]
np.inner(A, B.T)
[[ 0 13]
 [-2 29]]


# 目標3： 三次元以上の配列での@演算子とdot関数の違いを確認する

In [ ]:
import numpy as np

A = np.arange(12).reshape((2, 3, 2))
B = np.arange(12).reshape((2, 2, 3))

print("配列A：" , A.shape)
print(A)

print("配列B：" , B.shape)
print(B)

print("配列B.T：" , B.T.shape)
print(B.T)

配列A： (2, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
配列B： (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
配列B.T： (3, 2, 2)
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


In [ ]:
print("@演算子による内積：", (A @ B).shape) # リスト5の続き
print(A @ B)

print("dot関数による内積：" , np.dot(A, B).shape)
print(np.dot(A, B))

print("inner関数による内積：" , np.inner(A, B.T).shape)
print(np.inner(A, B.T))

@演算子による内積： (2, 3, 3)
[[[  3   4   5]
  [  9  14  19]
  [ 15  24  33]]

 [[ 99 112 125]
  [129 146 163]
  [159 180 201]]]
dot関数による内積： (2, 3, 2, 3)
[[[[  3   4   5]
   [  9  10  11]]

  [[  9  14  19]
   [ 39  44  49]]

  [[ 15  24  33]
   [ 69  78  87]]]


 [[[ 21  34  47]
   [ 99 112 125]]

  [[ 27  44  61]
   [129 146 163]]

  [[ 33  54  75]
   [159 180 201]]]]
inner関数による内積： (2, 3, 3, 2)
[[[[  6   9]
   [  7  10]
   [  8  11]]

  [[ 18  33]
   [ 23  38]
   [ 28  43]]

  [[ 30  57]
   [ 39  66]
   [ 48  75]]]


 [[[ 42  81]
   [ 55  94]
   [ 68 107]]

  [[ 54 105]
   [ 71 122]
   [ 88 139]]

  [[ 66 129]
   [ 87 150]
   [108 171]]]]


In [ ]:
import numpy as np

A = np.ones((2, 4, 5, 3)) # 2×4×5×3の形で、全ての要素が1の配列
B = np.ones((2, 4, 3, 6)) # 2×4×3×6の形で、全ての要素が1の配列
C = np.ones((2, 3, 3, 6)) # 2×3×3×6の形で、全ての要素が1の配列

print((A @ B).shape)
print((A @ C).shape)

(2, 4, 5, 6)


ValueError: ignored

In [ ]:
import numpy as np

A = np.ones((2, 4, 5, 3)) 
B = np.ones((2, 4, 3, 6))
C = np.ones((2, 3, 3, 6))

print(np.dot(A, B).shape)  # 最後がn×k, k×mとなっている
print(np.dot(A, C).shape)
# 出力例：
# (2, 4, 5, 2, 4, 6)
# (2, 4, 5, 2, 3, 6)

(2, 4, 5, 2, 4, 6)
(2, 4, 5, 2, 3, 6)


In [ ]:
import numpy as np

A = np.ones((2, 4, 5, 3)) 
B = np.ones((2, 4, 3, 6))
C = np.ones((2, 3, 3, 6))

print(np.inner(B, C).shape)
print(np.inner(A, C).shape)

(2, 4, 3, 2, 3, 3)


ValueError: ignored

# 練習問題と解答例

## （1）ニューラルネットワークの入力値を求める

In [ ]:
import numpy as np

X = np.array([1, 1, 0])
W = np.array([[0.5, -0.4],
              [0.3, 0.2],
              [0.8, -0.1]])
b = 0.5

print(W.T @ X - b)

[ 0.3 -0.7]


## （2）指定した点を中心にベクトルを回転させる

In [ ]:
def move(Dx, Dy):
  return np.array([[1, 0, Dx],
                   [0, 1, Dy],
                   [0, 0, 1]])

def rotate(theta):
  return np.array([[np.cos(theta), -np.sin(theta), 0],
                   [np.sin(theta), np.cos(theta), 0],
                   [0, 0, 1]])

p = np.array([4, 5, 1])

print(move(2, 1) @ rotate(np.pi/6) @ move(-2, -1) @ p)

[1.73205081 5.46410162 1.        ]
